### ISSUE TITLE
Path Traversal in Template Name

### ISSUE THREAD

**Issue by MantisSTS** [PatrikFehrenbach/BugBountyBlueprint#1]
Hey, cool tool, just wanted to let you know that you can perform a path traversal in the template name:

![image](https://github.com/PatrikFehrenbach/BugBountyBlueprint/assets/818959/c87ec610-369b-4bca-bc87-f7c2745eea4f)

![image](https://github.com/PatrikFehrenbach/BugBountyBlueprint/assets/818959/da2655a7-7af3-4de9-8834-85b2ba80a1b3)

Anyway, keep up the good work! :)

**Comment by PatrikFehrenbach** [comment]
Hey @MantisSTS 

Thanks for this! i have created a branch that should fix this: https://github.com/PatrikFehrenbach/BugBountyBlueprint/tree/1-path-traversal-in-template-name 

it introduces a secure path

```def get_secure_path(base_path: str, user_input: str) -> str:
    result_path = os.path.abspath(os.path.join(base_path, user_input))
    if not result_path.startswith(base_path):
        raise HTTPException(status_code=400, detail="Invalid file name")
    return result_path
```

which shouldn't allow to go outside the path.
